// Copyright 2019 deltam

// Package perm provides a permutation generator based on group theory.
//
// This algorithm is based on below paper.
//
// [[1307.2549] Hamiltonicity of the Cayley Digraph on the Symmetric Group Generated by σ = (1 2 ... n) and τ = (1 2)](https://arxiv.org/abs/1307.2549)
package perm

import (
	"errors"
)

var ErrPermutationLengthIsTooShort = errors.New("Permutation length is too short: MUST be len(p) >= 3")

func Init(p []int) error {
	n := len(p)
	if n < 3 {
		return ErrPermutationLengthIsTooShort
	}
	for i := 0; i < n; i++ {
		p[i] = n - i - 1
	}
	OpSwap(p)
	return nil
}

func Step(p []int) (swapped bool) {
	if IsSwap(p) && !IsSmallCycleEnd(p) {
		OpSwap(p)
		return true
	}
	OpRotate(p)
	return false
}

func IsEnd(p []int) bool {
	n := len(p)
	return p[0] == n-3 && p[1] == n-2 && p[n-1] == n-1 && isReverse(p[2:n-1])
}

func IsSmallCycleEnd(p []int) bool {
	return isReverse(p)
}

func IsSwap(p []int) bool {
	n := len(p)
	m := p[1]
	r := p[2]
	if p[0] != n-1 && p[1] != n-1 {
		for i := 2; i < n; i++ {
			if p[i] == n-1 {
				r = p[(i+1)%n]
				break
			}
		}
	}
	return m == (r+1)%(n-1)
}

// SmallCycleIndex returns index on small cycle start from n-2,n-1,n-3,...,2,1.
// Index range is [0, 2(n-1)).
// Returns -1 if p is not contained small cycle.
func SmallCycleIndex(p []int) int {
	n := len(p)
	if p[0] != n-1 && p[1] != n-1 {
		return -1
	}
	for i := 2; i < n-1; i++ {
		if d := p[i] - p[i+1]; d != 1 && d != -(n-2) {
			return -1
		}
	}
	f := p[1]
	var swap int
	if p[1] == n-1 {
		swap = 1
		f = p[0]
	}
	all := 2 * (n - 1)
	idx := 2*(n-2-f) + swap
	return (idx - 1 + all) % all
}

func isReverse(p []int) bool {
	n := len(p)
	for i := 0; i < n; i++ {
		if p[i] != n-i-1 {
			return false
		}
	}
	return true
}

func OpRotate(p []int) {
	n := len(p)
	f := p[0]
	copy(p[0:n-1], p[1:n])
	p[n-1] = f
}

func OpSwap(p []int) {
	p[1], p[0] = p[0], p[1]
}
